### ISSUE TITLE
Further exasperate CA w/ 1000-sans and 10000-sans certs

### ISSUE THREAD

**Issue by marumari** [lgarron/badssl.com#112]
See if we can get them signed for the production 1000-sans.badssl.com and 10000-sans.badssl.com.

**Comment by marumari** [comment]
Consider them fully and completely exasperated.  Looks like you're got certs in your inbox, @lgarron.

**Comment by Hoverbear** [comment]
We should send them christmas presents. What about a 100,000 SANs CSR?
