### ISSUE TITLE
spoofed-favicon.badssl.com

### ISSUE THREAD

**Issue by marumari** [lgarron/badssl.com#113]
Hey, @lgarron?  I'm working on a new domain that's pretty neat:

![spoofed favicon](http://i.imgur.com/TBpQaFt.png)

Still need to do other browsers.  If you know where in the Chromium source tree that I could find the iconography for the lock icon, that would be a huge help.  :)

Thanks!

**Comment by marumari** [comment]
(both for Chrome and Chrome Mobile, as they seem to use different favicons)

**Comment by lgarron** [comment]
Try securityState* from https://code.google.com/p/chromium/codesearch#chromium/src/third_party/WebKit/Source/devtools/front_end/Images/&q=securitystatesecure&sq=package:chromium&type=cs and

**Comment by lgarron** [comment]
The actual new toolbar seems to use [ToolbarModelImpl::GetVectorIcon](https://code.google.com/p/chromium/codesearch#chromium/src/chrome/browser/ui/toolbar/toolbar_model_impl.cc&q=ToolbarModelImpl::GetVectorIcon&sq=package:chromium&type=cs&l=161), but I would use securityState* [from DevTools](https://code.google.com/p/chromium/codesearch#chromium/src/third_party/WebKit/Source/devtools/front_end/Images/&q=securitystatesecure&sq=package:chromium&type=cs).

For the (raster) desktop icon, try use GetIcon() above to search for the file name, e.g. [omnibox_https_valid.png](https://code.google.com/p/chromium/codesearch#search/&q=omnibox_https_valid.png&sq=package:chromium&type=cs)
If you want a faviconny one, steal the one from <https://https.cio.gov/> ; I made it for @konklone.

**Comment by lgarron** [comment]
Also, didn't we learn a long time ago not to put a favicon in the toolbar like that? :-P

**Comment by marumari** [comment]
Awesome!  Thank you!

**Comment by lgarron** [comment]
> by adapting the border of the Chrome icon to be sized correctly for a favicon.

(Also, to include a 32x32 size for Retina.)

**Comment by marumari** [comment]
And yes, you would think so.

The Wheel of Time turns, and ages come and pass, leaving memories that become legend. Legends fade to myth, and even myth is long forgotten when the Age that gave it birth comes again. In one Age, called the third age by some, an Age yet to come, an age long pass, a wind rose in the Mountains of Security Iconography. The wind was not the beginning. There are neither beginnings or endings to the turning of the Wheel of Time. But it was a beginning.

**Comment by lgarron** [comment]
> All of this has happened before and all of this will happen again.
![bsg](https://cloud.githubusercontent.com/assets/248078/11199730/341fa64e-8c85-11e5-8d63-1870e70171e0.png)

**Comment by marumari** [comment]
You guys created your own vector format?  SVG not good enough or something?

Anyways, I've got the Chrome Mobile icon without too much trouble, but I'm having trouble finding the Chrome Desktop icon anywhere besides in that .icon file.

**Comment by marumari** [comment]
Closing this out, although it needs to be added to the current home page.
