### ISSUE TITLE
eDell / Superfish subdomains?

### ISSUE THREAD

**Issue by lgarron** [lgarron/badssl.com#117]
i.e. famous certs with known private keys.

**Comment by Hoverbear** [comment]
I was just talking to @marumari about this. I have the private keys already and want to do this. :)

**Comment by Hoverbear** [comment]
@lgarron What do you think about the Atheros cert detailed https://www.duosecurity.com/blog/dude-you-got-dell-d-publishing-your-privates ? Could it also be of use?
