### ISSUE TITLE
revoked.badssl.com

### ISSUE THREAD

**Issue by LinusHb** [lgarron/badssl.com#120]
To check the revocation behaviour of various browsers, would be handy

**Comment by lgarron** [comment]
Great minds think alike. :-)

https://github.com/lgarron/badssl.com/issues/30

**Comment by marumari** [comment]
I came here assuming that @lgarron was referring to me.  Was sadly disappointed!  :sob:

**Comment by LinusHb** [comment]
@lgarron, ah that's great, very useful link ! :)
