### ISSUE TITLE
freak.badssl.com

### ISSUE THREAD

**Issue by LinusHb** [lgarron/badssl.com#121]
Way to check how the browser reacts to export grade RSA cryptography

**Comment by marumari** [comment]
See #24.  :)

**Comment by LinusHb** [comment]
Ah thanks for the heads up @marumari, still playing catchup here - I'll try and read up on the past issues down the line

**Comment by marumari** [comment]
Sounds good; no biggie!  I don't think there's a contributor to the project who hasn't made a duplicate issue.  :)
