### ISSUE TITLE
mixed-favicon uses explicit favicons

### ISSUE THREAD

**Issue by marumari** [lgarron/badssl.com#122]
mixed-favicon should probably remove the link tags for "shortcut icon" and "apple-touch-icon", as it's a bit confusing since those are loaded over HTTPS.

Alternatively, perhaps the implicit *and* explicit favicons should all be over http?  Either way, the mixed-favicon site is a bit... mixed at the moment.

**Comment by lgarron** [comment]
Fixed in 28673a2e17dc1a51c46e3ff402cd056836d58cc3 (due to an independent crbug, but hey... great minds think alike! ;-).
