### ISSUE TITLE
HSTS site could be more useful

### ISSUE THREAD

**Issue by marumari** [lgarron/badssl.com#13]
hsts.badssl.com doesn't really do anything.  It would be great if it had the following behavior:

- Disable redirect to https on http://hsts.badssl.com/?hsts

Then:

- When https://hsts.badssl.com/ initially loaded over HTTPS, set HSTS
- Redirect to http://hsts.badssl.com?hsts
- If it then correctly goes to https://hsts.badssl.com/?hsts, generate a green background.  If it instead retrieves http://hsts.badss.com/?hsts, generate a red background.

Right now, the site is simply setting Strict-Transport-Security and displaying a green background.  That really doesn't say much, because it'll generate a green background on everything from IE6 to the latest Chrome.

**Comment by lgarron** [comment]
Interesting idea. I do something similar for [mixed-content-test.appspot.com](https://mixed-content-test.appspot.com/).

`hsts.badssl.com` was *supposed* to have the use case that `hsts-preloaded.badssl.com` now serves, part of which is to generate unoverridable Chrome errors on subdomains. I guess that's not needed anymore.

I like your idea. Pull request plz? :-D

**Comment by marumari** [comment]
Sweet!  I'll get working on it and send you a pull request when it's ready.

**Comment by marumari** [comment]
Okay!  This is working now in e122e4e0f26d12e1063571b0f7810b4e027ac194.  :D  Even gave it a nice gradient on the home page!

**Comment by marumari** [comment]
Also I fixed the stupidly wrong time in my VM (thanks, Parallels!), so hopefully github won't be so confused on chronology anymore.

**Comment by marumari** [comment]
Oh, and I didn't touch hsts-proloaded.  I could give it the same treatment, if you'd like?

**Comment by lgarron** [comment]
> Okay! This is working now in e122e4e. :D Even gave it a nice gradient on the home page!

I was testing this, but kept feeling like the behaviour is a bit confusing; it took me a while to internalize the redirect. How would you feel about this?

- HTTP doesn't redirect
- HTTPS doesn't redirect (but sends an HSTS header).

I'd kind of also like an HSTS reset link similar to [mixed-content-test](https://mixed-content-test.appspot.com/), but I think simpler is better. It should be easy to understand exactly what's going on.

**Comment by marumari** [comment]
I mean you could do it that way, but the end result would be the same: when you click the link, you get a red page if you support HSTS and you get a green page if you don't; they don't even really see how the redirection is done.  From an end-user perspective, I don't know if it really matters how the sausage is made.  It's a perfect confirmation of whether or not the browser supports HSTS: it's actually testing to see if you can get back to the HTTP page after visiting the HTTPS page.

Also, in your scenario, if you just went to straight to the HTTP page, you would get a red error, but that would be incorrect if you hadn't visited the HTTPS site that had set HSTS.  So would then have to set a cookie that you could read to see if you had or hadn't visited the HSTS site.

**Comment by marumari** [comment]
I should note that I updated the original issue to discuss how it is done, if that makes more sense than trying to puzzle through it via reading the nginx config.

**Comment by marumari** [comment]
See: https://www.youtube.com/watch?v=6GU_p7VQLLk

For a demonstration of what it looks like to the end user.

**Comment by lgarron** [comment]
Hmm, I think I understand it now. You're trying to go for a fully automated just-visit-this-URL "does my browser support HSTS?" test. I've been focusing on isolated pieces of behaviour that a developer can use for testing.

I think a test would be useful, but it should have a more clear URL, e.g. `hsts.badssl.com/test-hsts-support`.

**Comment by marumari** [comment]
Sure, I can certainly rename the test.  I'm a bit confused on what you're asking for it.  Could you do a little writeup on what isolated pieces of behavior that you're looking to test?  That might make what you're asking for a bit clearer for me.  :)

Thanks!

**Comment by marumari** [comment]
FYI, fixed the redirect in 13827114f0e71d686a619dc06cfe930c547ba245.

**Comment by lgarron** [comment]
So, I've settled on something that hopefully solves the "HSTS support test" use case with minimal fuss. When the home page is served over HTTPS, it includes an HTTP resource. Iff HSTS is working, the resource is rewritten to HTTPS:

![screen shot 2015-05-14 at 19 53 52](https://cloud.githubusercontent.com/assets/248078/7646113/a3041760-fa73-11e4-87af-d2dadd668dfe.png)
![screen shot 2015-05-14 at 19 58 39](https://cloud.githubusercontent.com/assets/248078/7646115/a79ff1c2-fa73-11e4-9248-1ab87f620d2d.png)

No separate pages, not redirects, no Javascript, only tests on HTTPS. :-)

The only thing is that the image is mixed content (which marks the page as yellow in Chrome), but I think that's fine.

The test is currently live, but I'm in the middle of a bunch of refactoring of PR #11.

**Comment by marumari** [comment]
Other than not quite having the beautiful aesthetic that a lot of the website has, it seems like a fine solution and totally works for me.  I may play around with it a bit more once I get back in town, but it seems to be behaving properly as near as I can tell.  :)

Otherwise, I look forward to seeing what you come up with for PR #11.  Nice work!

**Comment by lgarron** [comment]
Alright, we're a bit prettier (and consistent with SHA-1) now:

![screen shot 2015-05-15 at 02 36 37](https://cloud.githubusercontent.com/assets/248078/7650437/4d9201ec-faab-11e4-81a6-956a9691d289.png)
![screen shot 2015-05-15 at 02 36 52](https://cloud.githubusercontent.com/assets/248078/7650439/4f73bf14-faab-11e4-9c48-5e957a6db714.png)

**Comment by marumari** [comment]
Looks great!  Fine work!  :)
