### ISSUE TITLE
[request] test https://www.cnnic.cn/ 

### ISSUE THREAD

**Issue by cj1324** [lgarron/badssl.com#130]
Related:
https://googleonlinesecurity.blogspot.hk/2015/03/maintaining-digital-certificate-security.html

**Comment by lgarron** [comment]
What kind of test? I don't think we can (or should) get a key signed by them.

eDell, etc. were different because the private keys were public.

**Comment by marumari** [comment]
Agreed.  Unless somebody here is a highly influential Chinese politician, I don't think we'd have the oomph to get a certificate issued off the revoked root anyways.

**Comment by lgarron** [comment]
Marking as `wontfix`. Feel free to comment if you have more details or reasons you'd like us to consider.
