### ISSUE TITLE
1000-sans.badssl.com asking for a client certificate?

### ISSUE THREAD

**Issue by riking** [lgarron/badssl.com#131]
For some reason, the server seems to be asking for a client certificate.

Chrome's error when connecting:

> Certificate-based authentication failed

>ERR_BAD_SSL_CLIENT_AUTH_CERT

>This server requires a certificate for authentication, and didn't accept the one sent by the browser. Your certificate may have expired, or the server may not trust its issuer. You can try again with a different certificate, if you have one, or you may have to obtain a valid certificate from elsewhere.

OpenSSL:

```
$ openssl s_client -connect 1000-sans.badssl.com:443 -servername 1000-sans.badssl.com
CONNECTED(00000003)
139767848613520:error:14077419:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert access denied:s23_clnt.c:769:
---
no peer certificate available
---
No client certificate CA names sent
---
SSL handshake has read 7 bytes and written 344 bytes
---
New, (NONE), Cipher is (NONE)
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
---
```

**Comment by marumari** [comment]
Hmm, I'm not seeing this error at all.  Chrome connects fine, and so does OpenSSL.  Are you still having this same issue?

**Comment by lgarron** [comment]
I'm also not seeing this. Could you try to do this on different computers/networks, to see if anything is tampering with your connection?

**Comment by riking** [comment]
@lgarron Well, it's gone now, I can load the site in Chrome 48 beta.
