### ISSUE TITLE
Jekyll build is broken with self-signed certs

### ISSUE THREAD

**Issue by marumari** [lgarron/badssl.com#133]
The current repo:

- Requires you to run make keys after every make jekyll -- this is very slow, and also requires you to install new roots :scream: 
- Copies a lot of certs needlessly
- Has issues with certificate generation: cert-generator puts them into self-signed; make install-keys fixes this, but you have to run this every time
- Doesn't set the proper permissions on this directory

make install-keys should *only* install keys, not install certificates.  That's because it requires root privileges to actually run.

**Comment by Hoverbear** [comment]
This was my bad, sorry!
