### ISSUE TITLE
expired.badssl.com - is down

### ISSUE THREAD

**Issue by jamesst20** [lgarron/badssl.com#143]
Hi,

Just wanted to tell you that expired.badssl.com is currently down or inaccessible.

Thanks

**Comment by marumari** [comment]
I checked on multiple systems, and it's up for me.  Down for Everyone Or Just Me also reports that it's up.  Maybe it's a problem with your system?

**Comment by lgarron** [comment]
I've checked on it a few times, and I haven't seen a problem, either. Closing for now.

**Comment by jamesst20** [comment]
Thank you, sorry for the late response, indeed it was just blocked by the college network.
