### ISSUE TITLE
mozilla-modern.badssl.com should NOT have SSL3

### ISSUE THREAD

**Issue by carstenmjonas** [lgarron/badssl.com#148]
For some reason, mozilla-modern.badssl.com has SSL3 enabled and is vulnerable to the POODLE attack. The actual mozilla modern configuration is TLS 1.2 only. Can this be fixed?

**Comment by marumari** [comment]
It doesn't, really.  What happens is that your client (correctly) isn't including the SNI field in the SSLv3 request.  So the site has no idea your requests are for mozilla-modern.badssl.com and therefore lets your handshake resolve.

The only true fix for this one is to either:
- Remove SSLv3 entirely
- Move SSLv3 sites to a separate IP address
- Move SSLv3 sites to a separate port

All of these have cost or complexity issues.

**Comment by carstenmjonas** [comment]
Interesting Does this happen even though my client's connection is using TLS 1.2?

**Comment by marumari** [comment]
I'm not sure I understand what you're asking.  Your client will connect with the highest common protocol version that you have in common.

Note that this is the configuration for Mozilla Modern:
ssl_protocols TLSv1.1 TLSv1.2;
