### ISSUE TITLE
HTTPS Public Key Pinning HPKP

### ISSUE THREAD

**Issue by mozfreddyb** [lgarron/badssl.com#15]
Would be great if badssl had a test for HPKP voilations.

**Comment by lgarron** [comment]
Before I forget: we should have a preloaded pinning violation like https://pinningtest.appspot.com/

**Comment by lgarron** [comment]
https://pinning-test.badssl.com should trigger a pinning failure in tomorrow's Chrome Canary: https://codereview.chromium.org/1413513003

**Comment by lgarron** [comment]
Whee!
![screen shot 2015-10-25 at 02 10 13](https://cloud.githubusercontent.com/assets/248078/10714838/a41a8b5a-7abd-11e5-8a2f-66db5be1807e.png)

**Comment by marumari** [comment]
Looks nice, now go to bed!

**Comment by rugk** [comment]
Nice, but you should not write: `This site is preloaded with a bad HPKP pin starting in Chrome 48`
Because [HPKP](https://developer.mozilla.org/en-US/docs/Web/Security/Public_Key_Pinning) is a name for the ["dynamic pinning"](https://github.com/lgarron/badssl.com/issues/88). 
So probably "preloaded key pinning" would be a better name to differentiate this.

----
BTW could you also open an issue for inclusion of this key pin in Firefox?

**Comment by lgarron** [comment]
> Because HPKP is a name for the "dynamic pinning".

I prefer to use `HSTS` and `HPKP` consistently to make them more recognizable.

As far as I understand, preloaded HPKP is still key pinning for HTTP – it just wasn't served using an HTTP header. (Whereas I the "H" distinguishes this mechanism from, say, the SSH `known_hosts` mechanism.)

Your link and [the spec](https://tools.ietf.org/html/rfc7469#section-2.7) are unclear on this; the most I can is a suggestive description of it as *trust on first use*. But I'd like to get it right; do you know of a good citation for it?

> BTW could you also open an issue for inclusion of this key pin in Firefox?

Will do.

**Comment by lgarron** [comment]
>> BTW could you also open an issue for inclusion of this key pin in Firefox?
>
> Will do.

Filed: https://bugzilla.mozilla.org/show_bug.cgi?id=1218515

**Comment by jkldgoefgkljefogeg** [comment]
I got no warning on Chromium 48.0.2564.116 (Developer Build) Ubuntu 15.10 (64-bit) and Firefox 44.0.2

**Comment by lgarron** [comment]
> I got no warning on Chromium 48.0.2564.116 (Developer Build) Ubuntu 15.10 (64-bit) and Firefox 44.0.2

Developer builds don't have HPKP enabled. Did you build this yourself?

**Comment by jkldgoefgkljefogeg** [comment]
I got the warning on 49.0.2623.64 (Official Build) beta-m (64-bit) Windows x64.

but not on 48.0.2564.116-0ubuntu0.15.10.1.1221 0 from Ubuntu wily

**Comment by timmc** [comment]
Same result here, no warning on Chromium `Version 53.0.2785.89 Built on 8.5, running on Debian 8.5 (64-bit)`. This is true on my work computer as well. Additionally, a coworker verified that Google Chrome on Linux *did* block access. Maybe Debian packages it weird?

**Comment by lgarron** [comment]
> Should I open a separate issue?

No, this is expected behaviour.
Non-official builds disable static key pinning data, to avoid stale entries whose updates are not controlled by Google.

**Comment by timmc** [comment]
Maybe worth a note, then, that the static test is only valid for Google Chrome.

**Comment by timmc** [comment]
Ah... and my Firefox ESR 45 probably "fails" the test because the static pins have expired! Yeah, I think some of these tests need a special marker indicating that they only work for some browser/version/build combinations and are not expected to work across the board.

**Comment by lgarron** [comment]
> tests need a special marker

This is not a bad idea, and we are working on improving the descriptions (#202).

However, this behaviour is known to most people who use badssl.com on a regular basis, and it's not *quite* our goal to cater to every use case, so I don't consider this a high priority right now.

Could you let us know more about your use case?

**Comment by timmc** [comment]
Well, the tagline of the repo is "Memorable site for testing clients against bad SSL configs." so I assumed it was for broader use than just on the official vendor-built binaries. When I found that neither of Chromium 53 or Firefox ESR 45 "passed" the pinning test I was all set to file bugs, then found this thread. So I think there's a lot of value in noting which tests are broadly applicable (e.g. no browser should accept expired certs) vs. specific to a particular set of builds (e.g. preloaded HPKP).

**Comment by lgarron** [comment]
> When I found that neither of Chromium 53 or Firefox ESR 45 "passed" the pinning test I was all set to file bugs, then found this thread.

So you were testing for HPKP support in your Chromium/Firefox installs? Sounds like a reasonable case. Could you file a more specific bug, so that you'll be in the loop when we update the language?
