### ISSUE TITLE
sha1-2017.badssl.com (SHA-1 expiring in 2017)

### ISSUE THREAD

**Issue by lgarron** [lgarron/badssl.com#16]

**Comment by lgarron** [comment]
(Less awesome) alternative: link to https://longtermsha-1.comodoca.com/

**Comment by marumari** [comment]
I say that they should hire us at three times our current salaries!

(Also they should just sign our cert!  I mean, c'mon!)

**Comment by lgarron** [comment]
![screen shot 2015-06-09 at 13 54 24](https://cloud.githubusercontent.com/assets/248078/8069396/1a0644f6-0eaf-11e5-893f-86fad5143837.png)

**Comment by marumari** [comment]
Nice work!  *tips her hat*
