### ISSUE TITLE
mozilla-[modern/intermediate/old].badssl.com (Mozilla configs)

### ISSUE THREAD

**Issue by lgarron** [lgarron/badssl.com#22]
Using settings from Mozilla's [TLS config generator](https://mozilla.github.io/server-side-tls/ssl-config-generator/).

- `mozilla-modern.badssl.com`
- `mozilla-intermediate.badssl.com`
- `mozilla-old.badssl.com`

Each of the pages should document when the config generator was last used to update the cipher suites for it.

**Comment by marumari** [comment]
Probably also cipherli.st would be good; they're the other major site that is referenced for TLS configurations.
