### ISSUE TITLE
Additional DH group sizes (768, 1024, etc.)

### ISSUE THREAD

**Issue by lgarron** [lgarron/badssl.com#35]
Carried on from [here](https://github.com/lgarron/badssl.com/issues/1#issuecomment-102495565).

**Comment by hotaru2k3** [comment]
https://weakdh.org/
https://groups.google.com/a/chromium.org/forum/#!topic/security-dev/WyGIpevBV1s

it looks like at least one browser will be rejecting <1024-bit DH soon.

**Comment by marumari** [comment]
Since the low water mark seems likely to change very soon, I'll get a dh1024 site (yellow) created today.
