### ISSUE TITLE
Everything bad in one place

### ISSUE THREAD

**Issue by lgarron** [lgarron/badssl.com#38]
i.e. SHA-1, RC4, mixed content

In Chrome, this would be useful to see the maximum number of warnings/messages.

**Comment by marumari** [comment]
But what would we name it?  That's the really tough decision!

**Comment by lgarron** [comment]
very.badssl.com/wow/such-mixed

**Comment by marumari** [comment]
lol

Alas, that doesn't hit the wrong.host warning.  such disappoint, wow

**Comment by lgarron** [comment]
> Alas, that doesn't hit the wrong.host warning. such disappoint, wow

For my use case (getting the most crammed connection info), that would actually be counter-productive, since all the identity warnings would be replaced by a single cert warning in Chrome. :-P

**Comment by marumari** [comment]
Hey, @lgarron?  Are you on IRC at all?  Sometimes these things would be much easier to figure out over IRC than infinite github messages back and forth.  :)

**Comment by lgarron** [comment]
Mission accomplished.
It doesn't overflow the connection info on Android, though. :-(
(I was hoping it would, since I wanted to test for that.)

![screen shot 2015-05-19 at 13 38 34](https://cloud.githubusercontent.com/assets/248078/7713439/9e2aacc4-fe2c-11e4-9edc-3873613418fd.png)

**Comment by lgarron** [comment]
> Hey, @lgarron? Are you on IRC at all? Sometimes these things would be much easier to figure out over IRC than infinite github messages back and forth. :)

I actually prefer conversations in separate issues. :-)

I used to be on IRC back when I had a single computer, but I haven't managed to set up a bouncer yet. :-(

**Comment by hickford** [comment]
https://tescobank.com comes close https://www.ssllabs.com/ssltest/analyze.html?d=tescobank.com

**Comment by lgarron** [comment]
> https://tescobank.com comes close https://www.ssllabs.com/ssltest/analyze.html?d=tescobank.com

I see your tescobank.com and raise you [upsconline.nic.in](https://www.ssllabs.com/ssltest/analyze.html?d=upsconline.nic.in) (as of Aug. 5). ;-)

![unnamed](https://cloud.githubusercontent.com/assets/248078/10681966/4c87b1ae-78e4-11e5-89be-7d51e6010534.png)

**Comment by lgarron** [comment]
very.badssl.com has been serving this purpose pretty well for my testing purposes.

**Comment by marumari** [comment]
Plus it has a super cute puppy!

Who's a cute puppy?  Oh, you are!  Yes you are!  *scritches*

**Comment by lgarron** [comment]
Are you a dog person or cat person?

I've made the fortunate mistake of following https://twitter.com/shibesbot recently. :-)

**Comment by marumari** [comment]
I enjoy both species equally, but Shiba Inus are so stupid cute that it's not fair.  They are amazing dogs, but they're so willful and full of energy that I think having another child would be less work. 

Also, thanks for the extra puppies in my twitter feed.   :)

**Comment by sydia1103** [comment]
Do you know what happened to this? According to SSL Labs, it only gets a B rating. If it was bad, it should be getting at least a C or F. https://www.ssllabs.com/ssltest/analyze.html?d=very.badssl.com 
![Screen Shot 2022-02-19 at 9 44 16 AM](https://user-images.githubusercontent.com/69560065/154807963-1ba62eb1-6a06-492f-a2d3-a96c6866c227.png)
