### ISSUE TITLE
browsers sometimes cache things after problems have been fixed

### ISSUE THREAD

**Issue by hotaru2k3** [lgarron/badssl.com#47]
i noticed that after disabling all DHE cipher suites in chrome, going to https://dh512.badssl.com/ still succeeded. it turned out that the browser was showing the page from cache, and clicking the reload button fixed it. but these tests should probably send headers to prevent browsers from caching results.

**Comment by lgarron** [comment]
I tried some settings last week, and it seems `Cache-Control: no-store` works best. `Cache-Control: max-age=0` and `Cache-Control: no-cache` seemed to have issues.

**Comment by lgarron** [comment]
(Thanks to @davidben for poking me about this.)
