### ISSUE TITLE
Generate subdomain HTML from templates

### ISSUE THREAD

**Issue by lgarron** [lgarron/badssl.com#59]
I still insist that the output is static, though. That way, everything can be served, rendered, and debugged more safely.

In addition, it has been very useful for testing that each page is a single resource (with scripts and styles inlined in the page).

**Comment by marumari** [comment]
Can we generate _all_ the sites from templates, including HTML and nginx configurations?

Maybe have a big JSON file that lists all the sites and have everything generated from that?

**Comment by lgarron** [comment]
> Can we generate all the sites from templates, including HTML and nginx configurations?

Maybe not the custom images and Javascript, but yeah, mostly. You wanna take it on? ;-)

**Comment by marumari** [comment]
I just need to convince my employer to give me a couple weeks to dedicate to it, but I'll look into it.  :)

**Comment by lgarron** [comment]
Phew, that was a lot of work.

**Comment by marumari** [comment]
Something is a bit screwed up.  The http-password site is gray instead of red, and the source looks like so:

  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="shortcut icon" href="/icons/favicon-.ico"/>
  <link rel="apple-touch-icon" href="/icons/icon-.png"/>
  <title>http-password.badssl.com</title>

**Comment by lgarron** [comment]
I think you caught a small window with a bad push. Could you check again?

**Comment by marumari** [comment]
Looks good now!  Thanks!

**Comment by marumari** [comment]
Maybe I'm a bit confused on this -- my first post-jekyll site -- but shouldn't all the configs be changed to serve from _site now?

**Comment by lgarron** [comment]
> Maybe I'm a bit confused on this -- my first post-jekyll site -- but shouldn't all the configs be changed to serve from _site now?

#86 ;-)

(I [deploy from `_site`](https://github.com/lgarron/badssl.com/blob/f728c2004e77437590a5aa33ea1f522264873a5c/Makefile#L63), so it hasn't been a priority for me. :-P)

**Comment by marumari** [comment]
Okay, what I will probably do is change all the domain conf files to serve their root out of _site.  It's by far the easiest way to make it work for us chumps that don't have own fancy-pants domains.

**Comment by lgarron** [comment]
> change all the domain conf files to serve their root out of _site.

Sounds good. Alternatively, I'd also be happy with a more natural name than `_site`, like `build.
`jekyll` should accept a `--destination ./build` argument.

Then again, `_site` is a Jekyll convention and Jekyll is about convention over configuration. I don't want to be picky.

**Comment by marumari** [comment]
Yeah, I'm perfectly fine with ```_site```.  Not picky either.
