### ISSUE TITLE
Some certificates are v1 certificates unnecessarily

### ISSUE THREAD

**Issue by briansmith** [lgarron/badssl.com#65]
https://self-signed.badssl.com, at least, is a v1 certificate. It would be better to make it a v3 certificate. Otherwise, an implementation that rejects v1 certificates will never test the self-signedness aspect of the certificate.

The same applies to any other v1 certificates in the set.

**Comment by briansmith** [comment]
Note also that v1 certificates are not supposed to contain v3 extensions. This means that a v1 certificate will also lack a subjectAltName extension.

In general, every certificate should have just one problem, unless the test is specifically testing the intersection of problems.

**Comment by marumari** [comment]
This is a problem with the particular self-signed cert that @lgarron is using.  The certs that cert-generator.sh uses do not have this problem:

```
$ openssl s_client -connect self-signed.badssl.com:443 -servername self-signed.badssl.com | openssl x509 -noout -text

Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number:
            f3:5f:5f:7c:55:f6:40:40
        Signature Algorithm: sha256WithRSAEncryption
        Issuer: C=US, ST=California, L=San Francisco, O=BadSSL, CN=*.badssl.com
        Validity
            Not Before: Jun  8 02:05:42 2015 GMT
            Not After : Jun  7 02:05:42 2017 GMT
        Subject: C=US, ST=California, L=San Francisco, O=BadSSL, CN=*.badssl.com
        [...]
```
Lucas, if you just want any self-signed cert, you can use the one that I just generated today:

```
-----BEGIN CERTIFICATE-----
MIIDhjCCAm6gAwIBAgIJAPNfX3xV9kBAMA0GCSqGSIb3DQEBCwUAMGIxCzAJBgNV
BAYTAlVTMRMwEQYDVQQIEwpDYWxpZm9ybmlhMRYwFAYDVQQHEw1TYW4gRnJhbmNp
c2NvMQ8wDQYDVQQKEwZCYWRTU0wxFTATBgNVBAMUDCouYmFkc3NsLmNvbTAeFw0x
NTA2MDgwMjA1NDJaFw0xNzA2MDcwMjA1NDJaMGIxCzAJBgNVBAYTAlVTMRMwEQYD
VQQIEwpDYWxpZm9ybmlhMRYwFAYDVQQHEw1TYW4gRnJhbmNpc2NvMQ8wDQYDVQQK
EwZCYWRTU0wxFTATBgNVBAMUDCouYmFkc3NsLmNvbTCCASIwDQYJKoZIhvcNAQEB
BQADggEPADCCAQoCggEBAJrEDW/pVUcQc0/6WiGmusFagyBUkR25QQXhfz516t+n
23M/V2E6N0JjuAnfkGyd0eMyN2fCY9Pot22Q8L2ZTfvtVBrqy8mGDg6uZ7NyBDYC
vjwStIwTbySe4/BtevBFt9AUtSq/FG2q2gXdUudIJ7EZkT+IjEZrGiWTmHgMuOA8
FnMHPDEgHPDCD6I/GeCYFHAWoqLpNX0TXOSOttuqrHBWBd2vEPqDBmDTsWSOLbrP
a7GQi9L+szHS8CfJG5c730HD2SIgHJiNxBrJHqSXxbKe5woyG5+sK5xbmIRFymOc
+tLH+FKa24ma/2TskNv6ESeONZToD/LTEuQFIzNreTcCAwEAAaM/MD0wCQYDVR0T
BAIwADALBgNVHQ8EBAMCBeAwIwYDVR0RBBwwGoIMKi5iYWRzc2wuY29tggpiYWRz
c2wuY29tMA0GCSqGSIb3DQEBCwUAA4IBAQA3oEKDomJ0yCaIub4/QT7rjnn5ZDJV
7A3FUSCB+ulv+AdoNJ2eGszDCcDpcNIsVUBNOTVWytmQMyLElLvtVubXYvUXWoHi
hCpbzbc+XQv6ZXLIRO4+a5gfIyDVb87mFYUWUnwfkao+0WupbaWg2+tglidRXuDY
o3ywHGswEAitOiA//brYScOe5Yz16pcNsH3svKs4L4nDQEjkU1u4MMEJ7MnXJRku
eLRs9QYhQRTKV9UFlrMCpf1KdbSkHCYFRJg51bvcXB0kWm8DJHvTlIlay0kyxhMl
mfm1YBbQqhfUVc1bTBLhIyotBl3vBFYiSd8s9ku3kHpVubFiFukE2o8p
-----END CERTIFICATE-----
```

**Comment by lgarron** [comment]
> The same applies to any other v1 certificates in the set.

As April suspected, the self-signed cert is the only `v1` cert (no doubt to my old CSR scripts). I'll update it tomorrow.

Is there any use case for testing clients that actually reject v1 certs?
(i.e. is it worth hunting to see if any CA will still sign a v1 cert? :-P)

**Comment by briansmith** [comment]
> Is there any use case for testing clients that actually reject v1 certs?
> (i.e. is it worth hunting to see if any CA will still sign a v1 cert? :-P)

Yes: [libwebpki](https://github.com/briansmith/webpki) does not support anything other than v3 certificates. That's how I found this issue in the first place.

Hopefully, you will not find a commercial CA that will issue a v1 certificate. They are required to add a subjectAltName extension and v1 certificates are not allowed to have extensions.

**Comment by lgarron** [comment]
`v3` cert is live.

**Comment by lgarron** [comment]
And thanks for sending me a cert, April. But I needed one for the existing private key. ;-)
