### ISSUE TITLE
null.badssl.com

### ISSUE THREAD

**Issue by DaKnOb** [lgarron/badssl.com#67]
We should definitely add a `NULL` / `eNULL` SSL/TLS that only supports this cipher. Authentication is done using RSA/ECC so it's good, but the content is not encrypted (which may be bad).

**Comment by lgarron** [comment]
Do you have an example of how to configure this in nginx?
I'm happy to add it if it's not too complicated.

**Comment by DaKnOb** [comment]
Instead of supporting any cipher like AES, just support "NULL"

**Comment by lgarron** [comment]
> Instead of supporting any cipher like AES, just support "NULL"

Cool. :-)
If you'd like to make a pull request, you can probably copy the setup from `rc4.badssl.com`.
Else, I'll do it next time I have a segment of time for badssl.com updates.

**Comment by lgarron** [comment]
I [tried adding](https://github.com/lgarron/badssl.com/compare/null) `null.badssl.com`, but I can't get Chrome or OpenSSL. Is there a use case where a client will actually connect using the cipher, or any other use?

**Comment by DaKnOb** [comment]
I've seen it configured but all my browsers don't seem to be able to access it (latest Safari, Chrome, Firefox on Mac OS X 10.10). I'll try with old cURL or old wget maybe but that's kind of deprecated so pretty much all browsers don't use it.

**Comment by DaKnOb** [comment]
Currently [Qualy's SSL Server Test](https://www.ssllabs.com/ssltest/index.html) [fails(!)](https://www.ssllabs.com/ssltest/analyze.html?d=null.badssl.com) to analyze this server..

**Comment by DaKnOb** [comment]
Using the `openssl` client on my Mac I get:

```
$ openssl s_client -connect null.badssl.com:443 -cipher NULL
CONNECTED(00000003)
4144:error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure:/SourceCache/OpenSSL098/OpenSSL098-52.40.1/src/ssl/s23_clnt.c:593:
```

**Comment by lgarron** [comment]
> I've seen it configured but all my browsers don't seem to be able to access it (latest Safari, Chrome, Firefox on Mac OS X 10.10). I'll try with old cURL or old wget maybe but that's kind of deprecated so pretty much all browsers don't use it.

Yeah, I didn't expect any browsers to connect, but they didn't give a particularly useful message to see if the server was configured correctly.

I realized that I needed a newer version of OpenSSL. I get the same result as you when I use a newer version.

Someday I'd like to find a good way to have one subdomain for each cipher suite, but I'll merge this for now.
