### ISSUE TITLE
mozilla-modern.badssl.com (+ intermediate, +old)

### ISSUE THREAD

**Issue by marumari** [lgarron/badssl.com#69]
The Mozilla TLS configurations are one of the most commonly used configurations on the internet:

https://wiki.mozilla.org/Security/Server_Side_TLS

As such, it would probably be nice to have a site for each level of recommendations.  Note that the Mozilla TLS configuration generator should make this pretty easy to do:

https://mozilla.github.io/server-side-tls/ssl-config-generator/

**Comment by lgarron** [comment]
Dupe of #22. It seems this is as good an ideas as ever. ;-)

**Comment by marumari** [comment]
Hah!  u r 2 smt 4 me!
