### ISSUE TITLE
Cert chain with too many certs

### ISSUE THREAD

**Issue by lgarron** [lgarron/badssl.com#76]

**Comment by marumari** [comment]
Ooo, this looks like a fun followup to 10000-sans.badssl.com.  How many should we target as "too many"?  I don't think I've ever seen a TLS chain go beyond four in the wild, but I think 100 sounds like a good target for this.

That work for you?

**Comment by marumari** [comment]
Looks like this is a duplicate of the previous issue, #75.  Or am I mistaken with that you're trying to say?

**Comment by lgarron** [comment]
I forgot if I had a separate purpose for this bug. Since I can't remember, let's close
