### ISSUE TITLE
Mixed content with HSTS

### ISSUE THREAD

**Issue by glestel** [lgarron/badssl.com#77]
Hello,

I noticed https://hsts.badssl.com/ includes mixed content because of the inclusion of `http://hsts.badssl.com/hsts-test/status.svg` and the same thing happens with https://preloaded-hsts.badssl.com/

**Comment by marumari** [comment]
This is by design: if HSTS is working, it'll retrieve the right image (the checkmark over HTTPS), and, if not, an X mark over HTTP.

Hopefully browsers will stop presenting mixed content warnings for content upgraded to HTTPS via HSTS.  :)

**Comment by lgarron** [comment]
> Hopefully browsers will stop presenting mixed content warnings for content upgraded to HTTPS via HSTS. :)

@mikewest once explained to me why this is a bad idea: It means that the mixed content status of a page becomes non-deterministic. When you include a resource from a non-preloaded HSTS domain using HTTP for the first time, the redirect needs to be treated as mixed content.

This means that sites will randomly show mixed content warnings the first few times you visit them, also depending on whether you visited *other* certain sites first. This makes debugging hard.

In addition, it can hide mixed content issues from developers after they've triggered connections to the relevant domains. To them, everything looks green – but users are not protected from those initial-visit mixed content errors, and clients that support HTTPS *but not HSTS* are not protected.

Other sites can avoid the chance of insecure entirely by using `upgrade-insecure-requests`, but that would defeat the test on hsts.badssl.com. But that reminds me, I've been meaning to make upgrade-insecure-requests.badssl.com

**Comment by lgarron** [comment]
Also, if we get more comments about this, we can add a more prominent explanation to the page itself. I dislike that, though. :-/

**Comment by marumari** [comment]
We've been talking about a number of ways to solve @mikewest's problems in this regards, such that it does behave deterministically, at least at Firefox.  :)

* In the case of what we have here, with an image being retrieved from the same origin, there's literally zero reason to treat it as mixed content.  HSTS was set for the domain before the image was retrieved and no requests were ever sent over HTTP.  There really shouldn't be a mixed content warning.
* For resources on other origins, you can trust them using 1-2 different methods:
   * If you do a preflight https request to that domain and it sets HSTS. You'd do this with a plain GET / request, with no headers.
   * If it sends a redirect to the same resource (same origin, etc.) except that the scheme has changed from http to https; this has a bunch of problems, but there might be ways to make it work.

Also, I think the FF Dev tools have recently changed such that they will always show this as an error to developers, even if FF release ever gets changed to behave differently with regards to mixed content.
