### ISSUE TITLE
Wrong result for upgrade test in Firefox

### ISSUE THREAD

**Issue by rugk** [lgarron/badssl.com#79]
https://upgrade.badssl.com/ claims Firefox 41.0.2 would support the `upgrade-insecure-requests` CSP directive. However that's not true:
![upgradeinsecurerequestsff41](https://cloud.githubusercontent.com/assets/11966684/10567650/783298be-760a-11e5-96b6-a114f330b265.PNG)

Have a look at the first error message:
`Content Security Policy: Couldn't process unknown directive 'upgrade-insecure-requests'`
So FF is certainly *not* upgrading this request if it does not even understand the directive.

[CSP 2](http://caniuse.com/#feat=contentsecuritypolicy2) is just very limited currently...

**Comment by marumari** [comment]
It fails for me in Firefox release, but works for me in Firefox Dev Edition.  So I'm not seeing the same behavior you are.

**Comment by marumari** [comment]
http://i.imgur.com/0Of2NQC.png

**Comment by lgarron** [comment]
> https://upgrade.badssl.com/ claims Firefox 41.0.2 would support the upgrade-insecure-requests

**Comment by lgarron** [comment]
> https://upgrade.badssl.com/ claims Firefox 41.0.2 would support the upgrade-insecure-requests CSP directive.

I don't see that claim. Am I missing something?

http://caniuse.com/#search=upgradeinsecurerequests lists Firefox 42 as the first version that supports the directive.

**Comment by rugk** [comment]
> http://caniuse.com/#search=upgradeinsecurerequests lists Firefox 42 as the first version that supports the directive.

Yes and as I'm using 41 it should *not* be supported.

But I found the cause of this issue: HTTPS Everywhere. It was updating the request... obviously. :laughing: 
I have created a PR there to fix this issue: https://github.com/EFForg/https-everywhere/pull/3111

**Comment by lgarron** [comment]
> But I found the cause of this issue: HTTPS Everywhere. It was updating the request... obviously.

Oh, good catch. Is there a way to ask HTTPS Everywhere not to upgrade any *.badssl.com domains?

**Comment by rugk** [comment]
There is: https://github.com/lgarron/badssl.com/issues/80
