### ISSUE TITLE
https-everywhere.badssl.com

### ISSUE THREAD

**Issue by rugk** [lgarron/badssl.com#80]
Because of https://github.com/lgarron/badssl.com/issues/79 I got the idea of adding this domain similar (or nearly  the same) as https://upgrade.badssl.com/. :smiley: 

It's also a bit advertising for [https-everywhere](https://www.eff.org/https-everywhere). :wink:

**Comment by lgarron** [comment]
I'm a fan of HTTPS Everywhere (I use it myself!), but I'm not sure what this subdomain would do. Is it a subdomain that would only be upgraded if you use the HTTPS Everywhere upgrade list?

**Comment by rugk** [comment]
> Is it a subdomain that would only be upgraded if you use the HTTPS Everywhere upgrade list?

Exactly. An upgrade test for HTTPS-Everywhere.
Even if we modify the ruleset completely like you suggested in https://github.com/EFForg/https-everywhere/pull/3111#issuecomment-149722475 we could explicitly add this subdomain.

**Comment by lgarron** [comment]
Adding a subdomain for `https-everywhere` seems a little useless to me, but I suppose it has a use, and cant hurt (apart from piling on to a list of domains, which is already pretty long).

I'd be happy to accept a PR that implements it similarly to hsts.badssl.com (serve both HTTP and HTTPS, no automatic redirect).
