### ISSUE TITLE
preload-hsts still serves HSTS header

### ISSUE THREAD

**Issue by rugk** [lgarron/badssl.com#82]
The subdomain preload-hsts still [serves the HSTS header](https://github.com/lgarron/badssl.com/blob/master/domains/hsts/preloaded-hsts.badssl.com.conf#L18). Can't this lead to unexpected behaviour where a browser which supports HSTS but not HSTS preloading still redirect to HTTPS if the site is not preloaded but was just visited once with that header?

**Comment by lgarron** [comment]
Yes, but unfortunately Firefox will not preload unless the domain sends the HSTS header [1]. I think the current behaviour is best. :-(

Also, the main motivation behind that subdomain was not to test whether a site is preloaded, but rather to have a domain that will reliably have HSTS for testing, i.e. to make [subdomain.preloaded-hsts.badssl.com](https://subdomain.preloaded-hsts.badssl.com/). It would be nice to also make it a test of whether the browser supports preloading, but the Firefox constraint prevents that (and I don't know about other browsers). @marumari may have input on that, though. :-(

[1] https://blog.mozilla.org/security/2012/11/01/preloading-hsts/

**Comment by marumari** [comment]
I think we follow the same procedure as every body else (ie, preload in the header), but I can ask dkeeler tomorrow.

**Comment by rugk** [comment]
Yes the "preload" directive has to be sent - however AFAIK only one time: when you add it to the list. Afterwards it can be removed.

Or am I wrong?

**Comment by marumari** [comment]
As far as I know, it's only to get it added.  But I'll ask tomorrow and find out.

**Comment by rugk** [comment]
The only thing I can image is: This preload list has to be updated from the Chromium one.
In this case the header could be fetched and possibly checked again...

**Comment by lgarron** [comment]
Yeah, Firefox only trusts the value up to 18 weeks from when they query. The header needs to be sent regularly, and I'd prefer to avoid any UA sniffing or one-off whitelisting.
