### ISSUE TITLE
Update https-everywhere.badssl.com to mention which release it was added to.

### ISSUE THREAD

**Issue by lgarron** [lgarron/badssl.com#84]
This is a follow-up to #83, pursuant to https://github.com/EFForg/https-everywhere/pull/3111

**Comment by rugk** [comment]
You can assign it to me if you want. :smiley:

**Comment by rugk** [comment]
https://github.com/EFForg/https-everywhere/pull/3111 was merged.

So now we have to pay attention when a new HTTPS-E version is released.
Additionally you should add a link to the top website so that this subdomain can be visited from them main page.

**Comment by lgarron** [comment]
> Additionally you should add a link to the top website so that this subdomain can be visited from them main page.

I don't think there is a common testing use case for this, so I'd prefer to leave it as an unlisted domain for now.
