### ISSUE TITLE
Doge can be mis-sized.

### ISSUE THREAD

**Issue by lgarron** [lgarron/badssl.com#94]
![screen shot 2015-10-30 at 12 49 29](https://cloud.githubusercontent.com/assets/248078/10856391/b4cd13d2-7f04-11e5-8e2d-c016ddef5d61.png)

**Comment by marumari** [comment]
I hadn't realized that we needed a 'critical priority' label until this very moment.

**Comment by marumari** [comment]
That said, I'm not really certain how you did this.  I can't replicate it in the clearly superior Firefox browser.

**Comment by lgarron** [comment]
Yeah, still not sure what's going on; I thought I had all the sizing right.

![screen shot 2015-10-30 at 15 57 39](https://cloud.githubusercontent.com/assets/248078/10859892/0346d128-7f1f-11e5-8fc4-8b76e34886c6.png)
