### ISSUE TITLE
Feature Request: Level-Up sound whenever my browser doesn't catch an issue.

### ISSUE THREAD

**Issue by nathan-at-least** [lgarron/badssl.com#95]
I felt pretty happy each time my browser loads a badssl page without displaying any issue. I would feel even happier though if my browser played some kind of (copylefted) level up sound and a glowing pulsing star incremented my "score".

Just a thought.

**Comment by lgarron** [comment]
While I do like fun stuff:

- I'd prefer to keep things simple.
- I think this would unfortunately be too obnoxious.
- Maintaining a cross-domain score is likely to be tricky, and might interact badly with intended tests.

If you really, really want this, I'd be happy to write you a Chrome extension for it. ;-P

**Comment by nathan-at-least** [comment]
This is quite reasonable, since it would shift this project from a useful infrastructure tool into more of a amusement.
